# foot terminal config

term=xterm-256color

font=JetBrainsMono Nerd Font:size=7
dpi-aware=yes
pad=4x4

[scrollback]
lines=5000

[cursor]
style=block
blink=no

[colors]
background=24273a
foreground=cad3f5

regular0=494d64
regular1=ed8796
regular2=a6da95
regular3=eed49f
regular4=8aadf4
regular5=f5bde6
regular6=8bd5ca
regular7=b8c0e0

bright0=5b6078
bright1=ed8796
bright2=a6da95
bright3=eed49f
bright4=8aadf4
bright5=f5dbe6
bright6=8bd5ca
bright7=a5adcb

selection-foreground=cad3f5
selection-background=5b6078

search-box-no-match=ed8796 24273a
search-box-match=24273a a6da95

urls=8aadf4

